services:
  development-database:
    image: postgres:17
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /var/run/postgresql:/var/run/postgresql:rw
      - pgdata:/var/lib/postgresql/data:rw

volumes:
  pgdata:
