# Generated by Django 4.2.1 on 2023-05-28 09:23

from django.contrib.postgres import constraints as pgconstraints
from django.contrib.postgres import fields as pgfields
from django.contrib.postgres import operations as pgoperations
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        pgoperations.BtreeGistExtension(),
        migrations.CreateModel(
            name="SignupRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("origin", models.SlugField()),
                ("target", models.URLField()),
                ("duration", pgfields.DateRangeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="signupredirect",
            constraint=pgconstraints.ExclusionConstraint(
                expressions=[("origin", "="), ("duration", "&&")],
                name="no-same-origin-overlaps",
            ),
        ),
    ]
