# Generated by Django 5.0.10 on 2024-12-14 07:50

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup_redirects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="signupredirect",
            options={
                "verbose_name": "presmerovanie",
                "verbose_name_plural": "presmerovania",
            },
        ),
        migrations.AlterField(
            model_name="signupredirect",
            name="duration",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                verbose_name="Trvanie"
            ),
        ),
        migrations.AlterField(
            model_name="signupredirect",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Názov"),
        ),
        migrations.AlterField(
            model_name="signupredirect",
            name="origin",
            field=models.SlugField(verbose_name="Skrátená adresa"),
        ),
        migrations.AlterField(
            model_name="signupredirect",
            name="target",
            field=models.URLField(verbose_name="Cieľová adresa"),
        ),
    ]
