# Generated by Django 4.2.1 on 2023-05-28 09:17

from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations


def create_default_superuser(apps: Apps, _):
    user_model = apps.get_model(settings.AUTH_USER_MODEL)

    user_model.objects.create_superuser(username="admin", password="temporary-password")


def remove_default_superuser(apps: Apps, _):
    user_model = apps.get_model(settings.AUTH_USER_MODEL)

    user_model.objects.get(username="admin").delete()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            create_default_superuser,
            remove_default_superuser,
        ),
    ]
